// WallpaperFilter.swift
import Foundation

enum WallpaperFilter: String, CaseIterable {
    case noFilter = "Original"
    case addictiveBlue = "Addictive Blue"
    case addictiveRed = "Addictive Red"
    case aden = "Aden"
    case brooklyn = "Brooklyn"
    case earlybird = "Earlybird"
    case gingham = "Gingham"
    case hudson = "Hudson"
    case inkwell = "Inkwell"
    case lark = "Lark"
    case lofi = "Lo-Fi"
    case maven = "Maven"
    case mayfair = "Mayfair"
    case moon = "Moon"
    case perpetua = "Perpetua"
    case reyes = "Reyes"
    case rise = "Rise"
    case slumber = "Slumber"
    case stinson = "Stinson"
    case toaster = "Toaster"
    case valencia = "Valencia"
    case walden = "Walden"
    case willow = "Willow"
    case xpro2 = "X-Pro II"
    case crema = "Crema"
    case ludwig = "Ludwig"
    case sierra = "Sierra"
    case skyline = "Skyline"
    case dogpatch = "Dogpatch"
    case vesper = "Vesper"
    case amaro = "Amaro"
}
