// WallpaperFilter.swift
import Foundation

enum WallpaperFilter: String, CaseIterable {
    case noFilter = "Original"
    case addictiveBlue = "Addictive Blue"
    case addictiveRed = "Addictive Red"
    case aden = "Aden"
    case brooklyn = "Brooklyn"
    case earlybird = "Earlybird"
    case gingham = "Gingham"
    case hudson = "Hudson"
    case inkwell = "Inkwell"
    case lark = "Lark"
    case lofi = "Lo-Fi"
    case maven = "Maven"
    case mayfair = "Mayfair"
    case moon = "Moon"
    case perpetua = "Perpetua"
    case reyes = "Reyes"
    case rise = "Rise"
    case slumber = "Slumber"
    case stinson = "Stinson"
    case toaster = "Toaster"
    case valencia = "Valencia"
    case walden = "Walden"
    case willow = "Willow"
    case xpro2 = "X-Pro II"
    case crema = "Crema"
    case ludwig = "Ludwig"
    case sierra = "Sierra"
    case skyline = "Skyline"
    case dogpatch = "Dogpatch"
    case vesper = "Vesper"
    case amaro = "Amaro"
    
    /// Shortened display name for consistent UI spacing
    var displayName: String {
        switch self {
        case .noFilter: return "Original"
        case .addictiveBlue: return "Add. Blue"
        case .addictiveRed: return "Add. Red"
        case .aden: return "Aden"
        case .brooklyn: return "Brooklyn"
        case .earlybird: return "Earlybird"
        case .gingham: return "Gingham"
        case .hudson: return "Hudson"
        case .inkwell: return "Inkwell"
        case .lark: return "Lark"
        case .lofi: return "Lo-Fi"
        case .maven: return "Maven"
        case .mayfair: return "Mayfair"
        case .moon: return "Moon"
        case .perpetua: return "Perpetua"
        case .reyes: return "Reyes"
        case .rise: return "Rise"
        case .slumber: return "Slumber"
        case .stinson: return "Stinson"
        case .toaster: return "Toaster"
        case .valencia: return "Valencia"
        case .walden: return "Walden"
        case .willow: return "Willow"
        case .xpro2: return "X-Pro II"
        case .crema: return "Crema"
        case .ludwig: return "Ludwig"
        case .sierra: return "Sierra"
        case .skyline: return "Skyline"
        case .dogpatch: return "Dogpatch"
        case .vesper: return "Vesper"
        case .amaro: return "Amaro"
        }
    }
}
